# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-06 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0010_auto_20160105_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(max_length=250, verbose_name='title'),
        ),
    ]
